### ISSUE TITLE
Enhancement: add the formatting plugin Spotless

### ISSUE THREAD

**Issue by codespearhead** [appiepollo14/quarkus-realworld-api#78]
## Enhancement Proposal (I can't add labels)

Add spotless [1] as a dependency:

### ./pom.xml
```xml
...
<properties>
    <spotless.version>2.43.0</spotless.version>
</properties>
...
<build>
   <plugins>
      <plugin>
         <groupId>com.diffplug.spotless</groupId>
         <artifactId>spotless-maven-plugin</artifactId>
         <version>${spotless.version}</version>
      <executions>
        <execution>
          <goals>
            <goal>apply</goal>
          </goals>
          <phase>validate</phase>
        </execution>
      </executions>
         <configuration>
            <java>
               <googleJavaFormat />
               <removeUnusedImports />
            </java>
         </configuration>
      </plugin>
   </plugins>
</build>
```

### .github/workflows/maven.yml

```yml
      - name: Cache Maven dependencies
        ...

      - name: Run Spotless check
        run: ./mvnw spotless:check
```

[1] https://github.com/diffplug/spotless
